# Data
path: C:/Users/marcelo.goto/Desktop/yolo-keypoints/pose-detection-keypoints-estimation-yolov8/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [21, 2]  # [number of keypoints, number of dim]
flip_idx: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

# Classes
names:
  0: hand
